workers_dev = true
name = "nqesh-reviewer"
compatibility_date = "2025-03-02"
compatibility_flags = ["nodejs_compat"]
main = "./build/server/index.js"
assets = { directory = "./build/client/" }

[vars]

[[d1_databases]]
binding = "DB"
database_name = "nqesh-react-router"
database_id = "0fbd5d77-cd09-40b1-9d2c-9a56e7cb6ca4"
migrations_dir = "drizzle"

[placement]
mode = "smart"

[observability]
enabled = true
head_sampling_rate = 1